In [3]:
#Importing the necessary libararies.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#Reading the dataset

df=pd.read_csv('CAR DETAILS.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [6]:
# Learning the dataset
print(df.shape)
print(df.columns)
print(df.dtypes)

#Number of rows= 4340 columns=8

(4340, 8)
Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')
name             object
year              int64
selling_price     int64
km_driven         int64
fuel             object
seller_type      object
transmission     object
owner            object
dtype: object

In [7]:
# Checking for the NULL Values.
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [9]:
#Checking for the duplicates

df.duplicated().sum()

0

In [8]:
#Dropping the duplicates
df.drop_duplicates(inplace=True)

df.duplicated().sum()

0

In [10]:
# Checking the columns with the object dataype & performing the encoding.
df.dtypes

name             object
year              int64
selling_price     int64
km_driven         int64
fuel             object
seller_type      object
transmission     object
owner            object
dtype: object

In [11]:
# We will perform the encoding onto the fuel, seller_type, transmission, owner

#Fuel Column
print(df['fuel'].value_counts())

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['fuel']=lb.fit_transform(df['fuel'])

print('After Label Encoding')
print(df['fuel'].value_counts())

#By looking at the code we can say that Disel is encoded as the 1, Petrol is encoded as 4, CNG is encoded as 0, LPG is encoded as the 3,
#Electric is encoded as the 2

fuel
Diesel      1800
Petrol      1717
CNG           37
LPG           22
Electric       1
Name: count, dtype: int64
After Label Encoding
fuel
1    1800
4    1717
0      37
3      22
2       1
Name: count, dtype: int64

In [12]:
# Encoding the seller_type
print(df['seller_type'].value_counts())

df['seller_type']=lb.fit_transform(df['seller_type'])

print('After Label Encoding')
print(df['seller_type'].value_counts())

#Individual is encoded as the 1, Dealer encoded as the 0, Trustmark Dealer is encoded as 2.

seller_type
Individual          2832
Dealer               712
Trustmark Dealer      33
Name: count, dtype: int64
After Label Encoding
seller_type
1    2832
0     712
2      33
Name: count, dtype: int64

In [13]:
# Encoding the transmission
print(df['transmission'].value_counts())

df['transmission']=lb.fit_transform(df['transmission'])

print('After Label Encoding')
print(df['transmission'].value_counts())

#Manual is encoded as 1, automatic is encoded as 0.

transmission
Manual       3265
Automatic     312
Name: count, dtype: int64
After Label Encoding
transmission
1    3265
0     312
Name: count, dtype: int64

In [14]:
# Encoding the owner
print(df['owner'].value_counts())

df['owner']=lb.fit_transform(df['owner'])

print('After Label Encoding')
print(df['owner'].value_counts())

#1st owner is encoded as 0, 2nd owner is encoded as 2, 3rd owner is encoded as 4, 4th & above owner is encoded as 1, Test Drive encoded as 3

owner
First Owner             2218
Second Owner             978
Third Owner              289
Fourth & Above Owner      75
Test Drive Car            17
Name: count, dtype: int64
After Label Encoding
owner
0    2218
2     978
4     289
1      75
3      17
Name: count, dtype: int64

In [15]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,4,1,1,0
1,Maruti Wagon R LXI Minor,2007,135000,50000,4,1,1,0
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,1,1,0
3,Datsun RediGO T Option,2017,250000,46000,4,1,1,0
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,1,1,2

In [23]:
#Taking some sample data & storing it into another CSV file.

df_sample=df.sample(20)
df_sample.head()

df_sample.to_csv('samplecar.csv')

In [16]:
#Preparing the data set for the Machine Learning.

# Problem statement for the machine learning model is to predict the selling price using the regression algorithm

df_reg=df.drop('name',axis=1) #dropping of the name column
df_reg

      year  selling_price  km_driven  fuel  seller_type  transmission  owner
0     2007          60000      70000     4            1             1      0
1     2007         135000      50000     4            1             1      0
2     2012         600000     100000     1            1             1      0
3     2017         250000      46000     4            1             1      0
4     2014         450000     141000     1            1             1      2
...    ...            ...        ...   ...          ...           ...    ...
4335  2014         409999      80000     1            1             1      2
4336  2014         409999      80000     1            1             1      2
4337  2009         110000      83000     4            1             1      2
4338  2016         865000      90000     1            1             1      0
4339  2016         225000      40000     4            1             1      0

[3577 rows x 7 columns]

In [20]:
#spliting the dataset into the dependent & independent variable

x=df_reg.drop('selling_price',axis=1)
y=df_reg['selling_price']
print(x.shape)
print(y.shape)

(3577, 6)
(3577,)

In [27]:
#Fetaure Scaling onto the x (independent data)
col_names=x.columns
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

x_sc=sc.fit_transform(x)
x=pd.DataFrame(x_sc,columns=col_names)
x.head()

       year  km_driven      fuel  seller_type  transmission     owner
0 -1.402566   0.015754  1.032723     0.457384      0.309126 -0.708886
1 -1.402566  -0.404650  1.032723     0.457384      0.309126 -0.708886
2 -0.226418   0.646360 -0.956177     0.457384      0.309126 -0.708886
3  0.949731  -0.488731  1.032723     0.457384      0.309126 -0.708886
4  0.244042   1.508188 -0.956177     0.457384      0.309126  0.857318

In [46]:
#Spiliting the data into the training & testing

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=35)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2861, 6)
(716, 6)
(2861,)
(716,)

In [47]:
#Creating the evalutaion matrix for the regression model
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

def reg_eval(y,ypred):
    print('MAE',mean_absolute_error(y,ypred))
    print('MSE',mean_squared_error(y,ypred))
    print('RMSE',np.sqrt(mean_squared_error(y,ypred)))
    print('R2 score',r2_score(y,ypred))
    print('\n')

def model_score(model):
  print('Training Score',model.score(x_train,y_train))
  print('Testing Score',model.score(x_test,y_test))

In [48]:
#Creating the linear regression model & evaluating it

from sklearn.linear_model import LinearRegression
model_lin=LinearRegression()
model_lin.fit(x_train,y_train)

ypred1=model_lin.predict(x_test)

print('Evalutaing the Model\n')
reg_eval(y_test,ypred1)
model_score(model_lin)

Evalutaing the Model

MAE 216430.94823167534
MSE 189264311366.87106
RMSE 435045.18313259265
R2 score 0.3290014947396148


Training Score 0.4534883944085164
Testing Score 0.3290014947396148

In [60]:
#Creating the KNN Regression model

from sklearn. neighbors import KNeighborsRegressor
model_knn=KNeighborsRegressor(n_neighbors=11)
model_knn.fit(x_train,y_train)

ypred2=model_knn.predict(x_test)

print('Evalutaing the Model\n')
reg_eval(y_test,ypred2)
model_score(model_knn)

Evalutaing the Model

MAE 192262.87417470792
MSE 167495402430.84912
RMSE 409262.0217303935
R2 score 0.40617877793542057


Training Score 0.5999135021788446
Testing Score 0.40617877793542057

In [67]:
#Performing the ridge & lasso regression:-

from sklearn.linear_model import Lasso, Ridge

model_lasso=Lasso(alpha=5)
model_lasso.fit(x_train,y_train)
ypred3=model_lasso.predict(x_test)

print('Evalutaing the Model\n')
reg_eval(y_test,ypred3)
model_score(model_lasso)

Evalutaing the Model

MAE 216430.7689331619
MSE 189264272543.08392
RMSE 435045.13851218234
R2 score 0.32900163238153446


Training Score 0.4534883944036655
Testing Score 0.32900163238153446

In [71]:
model_ridge=Ridge(alpha=0.5)
model_ridge.fit(x_train,y_train)
ypred4=model_ridge.predict(x_test)

print('Evalutaing the Model\n')
reg_eval(y_test,ypred4)
model_score(model_ridge)

Evalutaing the Model

MAE 216418.18144903585
MSE 189258045748.58112
RMSE 435037.9819608641
R2 score 0.32902370822760274


Training Score 0.4534883840125419
Testing Score 0.32902370822760274

Selecting the best model out of the four:- <br>

1.We are not selecting the linear regssion model beacuse it has less model score than the KNN model.Linear regression model does not have any hyperparameter to tune it.<br>

2.Into the ridge & lasso regression we have tried various values of alpha. But model score does not change & it also has less model score than the KNN Model. <br>

3. Hence, we have selected the KNN regression model as the best fit model for this problem statement.<br>

In [84]:
#Saving the best fit model

import pickle

pickle.dump(model_knn,open('best_model.pkl','wb'))

#Loding the model again

loaded_model=pickle.load(open('best_model.pkl','rb'))

#Aplying the loaded model onto the sample data

df_sample.head()

#Setting x & y

x_sample=df_sample.drop('selling_price',axis=1)
y_sample=df_sample['selling_price']

#Feature sacaling of X
x_sc=sc.fit_transform(x_sample)
x_sample=pd.DataFrame(x_sc,columns=col_names)

#Genrating the predictions using the loaded model

y_pred=loaded_model.predict(x_sample)
print('Below are the predictions\n')
print(y_pred)

print('\nBelow are the actual values\n')
print(y_sample)

#Testing the model

reg_eval(y_sample,y_pred)
print('Testing Score', loaded_model.score(x_sample,y_sample))

Below are the predictions

[ 310454.45454545 2578636.36363636  175727.27272727   95727.27272727
  594454.54545455 2665909.09090909  430454.54545455  248090.90909091
  250000.          316363.54545455  451454.54545455  404727.18181818
  539000.          391454.54545455  128090.90909091  947272.72727273
  254090.90909091  739545.45454545  533636.36363636  189636.27272727]

Below are the actual values

3472     300000
1026    3050000
2983     550000
3653     100000
412      475000
4042    1100000
2435     700000
817      220000
3128     325000
2433     320000
568      385000
870      450000
3519     600000
3044     250000
2730      40000
3833     650000
2857     325000
3716     495000
3418     250000
2206     300000
Name: selling_price, dtype: int64
MAE 216550.0090909091
MSE 159580083584.29913
RMSE 399474.75963357073
R2 score 0.5835247058857174


Testing Score 0.5835247058857174